# List of tasks doctor will run
tasks:
# Dismiss stale reviews in PR when new commits are pushed.
- name: dismissStaleReviews
# Check whether pull request contains fixup commits.
- name: blockFixup
# Check Jenkins job status
- name: checkJobStatus
  config:
    jobs:
    - name: master-acceptance-tests-regatta
