run:
  timeout: 5m
  modules-download-mode: readonly
linters:
  disable-all: true
  enable:
  - bodyclose
  - gci
  - godot
  - gofumpt
  - goheader
  - goimports
  - gomoddirectives
  - gomodguard
  - gosec
  - gosimple
  - govet
  - gosec
  - ineffassign
  - staticcheck
  - stylecheck
  - testifylint
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - wastedassign
  - whitespace

linters-settings:
  gosec:
    excludes:
    - G104
    - G304
    - G401
    - G404
    - G501

  goheader:
    template: Copyright JAMF Software, LLC

issues:
  exclude-dirs:
  - raft

  exclude-rules:
  # Exclude some linters from running on tests files.
  - path: _test\.go
    linters:
    - ineffassign
    - gosec

  - linters:
    - staticcheck
    text: "SA4006:" #SA4006: this value of `not_used` is never used (staticcheck)
