apiVersion: v1
kind: Service
metadata:
  name: {{ template "meta.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "meta.name" . }}
    chart: {{ template "meta.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    team: {{ .Values.team }}
spec:
  selector:
    app: {{ template "meta.name" . }}
  ports:
  - name: http
    targetPort: http
    port: 8080
