apiVersion: v1

name: regatta
namespace: {{ env "FI_NAME" | default "default_fi_instance" }}

charts:
- .:
    values:
      replicas: 1
      noServiceMonitor: true
      image:
        repository: {{ env "REPOSITORY_URL" | default "371487436103.dkr.ecr.eu-west-1.amazonaws.com/regatta" | quote }}
        tag: {{ env "TAG" | default "latest" | quote }}
        imagePullPolicy: IfNotPresent
      externalLoadBalancer:
        externalDomain: reg.{{ env "FI_NAME" }}.fi2.wandera.cz
        loadBalancerSourceRanges:
        - "54.246.181.160/32" # VPN
      reflectionAPI:
        enabled: true
      persistence:
        storage:
          storageClassName: gp2-b
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
      resources:
        limits:
          cpu: 1
          memory: 1500Mi
        requests:
          cpu: 200m
          memory: 500Mi
      kafka:
        brokers: "core-kafka-bootstrap:9092"
        groupID: "regatta-fi-0"
        tls: false
