apiVersion: v1

name: regatta
namespace: regatta

charts:
- .:
    values:
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 0.5Gi
      mode: leader
      kind: true
      noServiceMonitor: true
      image:
        repository: regatta
        imagePullPolicy: IfNotPresent
        tag: {{ env "TAG" | default "latest" | quote }}
      reflectionAPI:
        enabled: true
      priorityClassName: false
      affinity:
        podAntiAffinity:
          topologyKey: kubernetes.io/hostname
      kafka:
        enabled: false
      persistence:
        storage:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      raft:
        initialMembers: "1=regatta-0.regatta.regatta.svc.cluster.local:5012,2=regatta-1.regatta.regatta.svc.cluster.local:5012,3=regatta-2.regatta.regatta.svc.cluster.local:5012"
      replication:
        server:
          enabled: false
      maintenance:
        backup:
          enabled: true
          bucket: "s3://NONEXISTING_BUCKET"
      tables:
        names: applicable-cellular-data-policy,applicable-wifi-data-policy,applicable-secure-policy,applicable-device-secure-policy,dns-search-domain,activation-profile,device-identity,regatta-test,performance_test_ghz_table_1,performance_test_ghz_table_2,performance_test_ghz_table_3,performance_test_ghz_table_4,performance_test_ghz_table_5,block-ca-cert-chains,customer-block-pages,customer-settings,applicable-gateway-rules
