apiVersion: v1

name: regatta
namespace: regatta

charts:
- .:
    values:
      kind: true
      noServiceMonitor: true
      image:
        repository: regatta
        imagePullPolicy: IfNotPresent
        tag: {{ env "TAG" | default "latest" | quote }}
      reflectionAPI:
        enabled: true
      kafka:
        enabled: false
      affinity: true
      persistence:
        storage:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      raft:
        initialMembers: "1=regatta-0:5012,2=regatta-1:5012,3=regatta-2:5012"
