apiVersion: v1

name: regatta
namespace: {{ env "FI_NAME" | default "default_fi_instance" }}

charts:
- .:
    values:
      image:
        repository: {{ env "REPOSITORY_URL" | default "371487436103.dkr.ecr.eu-west-1.amazonaws.com/regatta"  | quote }}
        tag: {{ env "TAG" | default "latest" | quote }}
