apiVersion: v1

name: regatta
namespace: {{ env "FI_NAME" | default "default_fi_instance" }}

charts:
- .:
    values:
      mode: leader
      replicas: 1
      podDisruptionBudget:
        enabled: false
      safeToEvict: true
      noServiceMonitor: true
      image:
        repository: {{ env "REPOSITORY_URL" | default "371487436103.dkr.ecr.eu-west-1.amazonaws.com/regatta" | quote }}
        tag: {{ env "TAG" | default "latest" | quote }}
        imagePullPolicy: IfNotPresent
# Note: enable only if you need to have regatta available externally
#      externalLoadBalancer:
#        externalDomain: reg.{{ env "FI_NAME" }}.fi2.wandera.cz
#        loadBalancerSourceRanges:
#        - "54.246.181.160/32" # VPN
      reflectionAPI:
        enabled: true
      priorityClassName: false
      affinity: false
      persistence:
        storage:
          storageClassName: ebs-gp3-zone-agnostic
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
      storage:
        blockCacheSize: 398458880
      resources:
        limits:
          cpu: 200m
          memory: 600Mi
        requests:
          cpu: 100m
          memory: 200Mi
      startupProbe:
        initialDelaySeconds: 10
      kafka:
        brokers: "core-kafka-bootstrap:9092"
        groupID: "regatta-fi-0-tables"
        tls: false
        checkTopics: true
      replication:
        server:
          enabled: false
      maintenance:
        server:
          enabled: false
