apiVersion: v1

name: regatta
namespace: regatta

charts:
- .:
    values:
      mode: leader
      kind: true
      noServiceMonitor: true
      image:
        repository: regatta
        imagePullPolicy: IfNotPresent
        tag: {{ env "TAG" | default "latest" | quote }}
      reflectionAPI:
        enabled: true
      priorityClassName: false
      affinity:
        podAntiAffinity:
          topologyKey: kubernetes.io/hostname
      kafka:
        enabled: false
      persistence:
        storage:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      raft:
        initialMembers: "1=regatta-0.regatta.regatta.svc.cluster.local:5012,2=regatta-1.regatta.regatta.svc.cluster.local:5012,3=regatta-2.regatta.regatta.svc.cluster.local:5012"
      replication:
        server:
          enabled: false
