# Default values for regatta
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicas: 3
team: delta

safeToEvict: false

image:
  repository: 371487436103.dkr.ecr.eu-west-1.amazonaws.com/regatta
  imagePullPolicy: Always

branch: master

resources:
  limits:
    cpu: 1
    memory: 1.5Gi
  requests:
    cpu: 500m
    memory: 1.5Gi

internalPort: 8443
metricsPort: 8079

tolerations: []
nodeSelector: {}
affinity:
  podAntiAffinity:
    topologyKey: kubernetes.io/hostname

raft:
  initialMembers: "1=regatta-0.regatta.regatta.svc.cluster.local:5012"
  rtt: 50ms

externalLoadBalancer: {}

reflectionAPI:
  enabled: false

persistence: {}

kafka:
  enabled: true
  brokers: ""
  checkTopics: false
  dialerTimeout: 10s
  groupID: ""
  topics: applicable-cellular-data-policy,applicable-wifi-data-policy,applicable-secure-policy,applicable-device-secure-policy
  tls: false
  serverCert: ""
  clientCert: ""
  clientKey: ""

kind: false

noServiceMonitor: false
