# Default values for regatta
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicas: 3
team: delta

image:
  repository: 371487436103.dkr.ecr.eu-west-1.amazonaws.com/regatta
  imagePullPolicy: Always

branch: master

resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

internalPort: 8443

tolerations: []
nodeSelector: {}
affinity: {}

raft:
  initialMembers: "1=regatta-0.regatta.regatta.svc.cluster.local:5012"

externalLoadBalancer: {}

reflectionAPI:
  enabled: false

persistence:
  hostPath: false

kafka:
  enabled: true
  brokers: ""
  dialerTimeout: 10s
  groupID: ""
  topics: applicable-cellular-data-policy,applicable-wifi-data-policy,applicable-secure-policy,applicable-device-secure-policy
  tls: false
  serverCert: ""
  clientCert: ""
  clientKey: ""

kind: false
