# Default values for regatta
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicas: 3
team: delta

# Either leader or follower
mode: follower

safeToEvict: false

image:
  repository: 371487436103.dkr.ecr.eu-west-1.amazonaws.com/regatta
  imagePullPolicy: Always

branch: master

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 2Gi

internalPort: 8443
metricsPort: 8079

replication:
  server:
    enabled: true
    port: 8444
    hostname: foo
  leaderAddress: bar
  logReplicationEnabled: false
  # 0 means unlimited
  maxSnapshotRecvBytesPerSecond: 0

priorityClassName: service-cluster-critical
tolerations: []
nodeSelector: {}
affinity:
  podAntiAffinity:
    topologyKey: kubernetes.io/hostname

raft:
  initialMembers: "1=regatta-0.regatta.regatta.svc.cluster.local:5012"
  rtt: 50ms
  snapshotEntries: 10000
  compactionOverhead: 5000
  # 0 means unlimited
  maxSnapshotRecvBytesPerSecond: 0
  maxSnapshotSendBytesPerSecond: 0
  heartbeatRTT: 4
  electionRTT: 100

externalLoadBalancer: {}

reflectionAPI:
  enabled: false

persistence: {}

kafka:
  enabled: true
  brokers: ""
  checkTopics: false
  dialerTimeout: 10s
  groupID: ""
  topics: applicable-cellular-data-policy,applicable-wifi-data-policy,applicable-secure-policy,applicable-device-secure-policy
  tls: false
  serverCert: ""
  clientCert: ""
  clientKey: ""

kind: false

noServiceMonitor: false

tables:
  names: applicable-cellular-data-policy,applicable-wifi-data-policy,applicable-secure-policy,applicable-device-secure-policy
