# Default values for regatta
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicas: 3
podDisruptionBudget:
  enabled: true
  minAvailable: 2
team: delta

# Either leader or follower
mode: follower

safeToEvict: false

image:
  repository: 371487436103.dkr.ecr.eu-west-1.amazonaws.com/regatta
  imagePullPolicy: Always

branch: master

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 2Gi

internalPort: 8443
metricsPort: 8079

replication:
  server:
    enabled: true
    port: 8444
    hostname: foo
  leaderAddress: bar
  logReplicationEnabled: false
  # 0 means unlimited
  maxSnapshotRecvBytesPerSecond: 0
  logRpcTimeout: 5m

maintenance:
  token: ""
  server:
    enabled: true
    port: 8445
  backup:
    enabled: false
    successfulJobsHistoryLimit: 4
    failedJobsHistoryLimit: 2
    schedule: "0 */4 * * *"
    bucket: ""

priorityClassName: service-cluster-critical
tolerations: []
nodeSelector: {}
affinity:
  podAntiAffinity:
    topologyKey: kubernetes.io/hostname

raft:
  initialMembers: "1=regatta-0.regatta.regatta.svc.cluster.local:5012"
  rtt: 50ms
  snapshotEntries: 10000
  compactionOverhead: 5000
  # 0 means unlimited
  maxSnapshotRecvBytesPerSecond: 0
  maxSnapshotSendBytesPerSecond: 0
  heartbeatRTT: 4
  electionRTT: 100

externalLoadBalancer: {}

reflectionAPI:
  enabled: false

storage:
  # 384MB default (each table will use up to 64MB for writes, the extra is then used to serve reads)
  blockCacheSize: 402653184

persistence: {}

kafka:
  enabled: true
  brokers: ""
  checkTopics: false
  dialerTimeout: 10s
  groupID: ""
  topics: applicable-cellular-data-policy,applicable-wifi-data-policy,applicable-secure-policy,applicable-device-secure-policy,carrier-predictor-v3
  tls: false
  serverCert: ""
  clientCert: ""
  clientKey: ""

kind: false

noServiceMonitor: false

tables:
  names: applicable-cellular-data-policy,applicable-wifi-data-policy,applicable-secure-policy,applicable-device-secure-policy,dns-search-domain,activation-profile,device-identity,block-ca-cert-chains,customer-block-pages,carrier-predictor-v3,customer-settings

alerts:
  grpcFailedRequests: 0
