{{- if not .Values.kind  }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "meta.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "meta.name" . }}
    chart: {{ template "meta.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  commonName: {{ template "meta.name" . }}.{{ .Release.Namespace }}.svc
  dnsNames:
  - "{{ template "meta.name" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.internalPort }}"
  - "{{ template "meta.name" . }}.{{ .Release.Namespace }}.svc.cluster.local"
  - "{{ template "meta.name" . }}.{{ .Release.Namespace }}:{{ .Values.internalPort }}"
  - "{{ template "meta.name" . }}.{{ .Release.Namespace }}"
  - "{{ template "meta.name" . }}:{{ .Values.internalPort }}"
  - "{{ template "meta.name" . }}"
{{ if .Values.externalLoadBalancer }}
  - {{ .Values.externalLoadBalancer.externalDomain }}
{{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-wandera-intermediary-ca
  secretName: {{ template "meta.name" . }}-cert
{{- else }}
  apiVersion: v1
kind: Secret
metadata:
  name: {{ template "meta.name" . }}-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "meta.name" . }}
    chart: {{ template "meta.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lRSWo0QnVPdFFSV3h2VUE0Q1VhTCtXakFOQmdrcWhraUc5dzBCQVFzRkFEQVMKTVJBd0RnWURWUVFLRXdkQlkyMWxJRU52TUNBWERURTRNREl5TWpFek5EQTFORm9ZRHpJeE16SXdNekl6TURVMApNRFUwV2pBU01SQXdEZ1lEVlFRS0V3ZEJZMjFsSUVOdk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQTBmK3J4dmcrUC9ZeEo5Um5qNHFQeXBleHJlOU9Bd0hmWUlmRHRCd1BmZlNOaG1hSmE2SXIKSm1QREFmcmtHbUF1OEUrMUVKTVJnZTdSNGpzK3k3bGovbnhTVEhRVzRpeFhXWU5hSHJYQjhUMnR5K2RXMlQrdApUV2FndEJrZ2RacUMrdDNBbG9SdERKQklGS1hjZDZ5SEE5cTl2ai9LUnRuYWZUUGpEWUQrbTRvYlI1dmhrRlltCjVvSkpvTGtjdVo4aEdyM01kekhGTUlQT0o1Qm01WUJZM3o0VExxR25tRHFoTDNwcU5IVzB4SFA3d0dFSk9UYWwKSS8zT3FSdGhBa0xMTXdVQ0hRY3BMdDFqMmpUYmF2b2RVU3I0aWJOWFRuNUwxeW5SR3RvemIyaUUrNGJabFJRWgpvUjBRMzJYeFBRK3ZrS3RhdGdYUzdFNnlpcS92VWM4OGhRSURBUUFCbzFvd1dEQU9CZ05WSFE4QkFmOEVCQU1DCkFxUXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFnQmdOVkhSRUUKR1RBWGdnbHNiMk5oYkdodmMzU0hCQUFBQUFDSEJIOEFBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUpnbwpockxKREtOOVZYaDZFWFl0YWVNeFJWRUlOdCtzd3JYTG94TmNObVJYWmI1dlgxMXlYOXVIV0NjSWFPSFpNNGM2CitaWmU2Z3RkVEdzd3J6bDd2QjVSSjVaSkV5cGowTWhBdkgvUE4wSjlXMGdYWWJ4ekk4MzlSUTJEcU5YRGpVN0kKYkVEbEtCU1NtRmIwVGpYVHVYaEhLeXZpTEVUQWJmMTQzWmI3TTFpOUwrVTVmaVBhcTJadDA3Tlg2ZDJTWWVNZAo3dWRYeXYvV2hXZlhLWWoySG9hOHNLZmNOcjJlNjhJa2JENmkxajl6WFNiT01mdnMxSlpncnlHcU5Jb0dET1B6CitNM1FodnZ1aVlKQ1NvT2hEcGgwcE5vVmVINE50YVZ3cVBlN3FNUG5pbTExQ0dRU2ZqenhtWk1GcXNvSklzUmUKbGlnL3ViTkpaYkM2b0ExWCt0ND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMGYrcnh2ZytQL1l4SjlSbmo0cVB5cGV4cmU5T0F3SGZZSWZEdEJ3UGZmU05obWFKCmE2SXJKbVBEQWZya0dtQXU4RSsxRUpNUmdlN1I0anMreTdsai9ueFNUSFFXNGl4WFdZTmFIclhCOFQydHkrZFcKMlQrdFRXYWd0QmtnZFpxQyt0M0Fsb1J0REpCSUZLWGNkNnlIQTlxOXZqL0tSdG5hZlRQakRZRCttNG9iUjV2aAprRlltNW9KSm9Ma2N1WjhoR3IzTWR6SEZNSVBPSjVCbTVZQlkzejRUTHFHbm1EcWhMM3BxTkhXMHhIUDd3R0VKCk9UYWxJLzNPcVJ0aEFrTExNd1VDSFFjcEx0MWoyalRiYXZvZFVTcjRpYk5YVG41TDF5blJHdG96YjJpRSs0YloKbFJRWm9SMFEzMlh4UFErdmtLdGF0Z1hTN0U2eWlxL3ZVYzg4aFFJREFRQUJBb0lCQUVOSHU3eGFxbThKcklRTApURWF6NlEvS2ZCV3k5dmFGc2hDV1RzQTB3VTNrZlRkVFFMSG9XaFRKbjUvUnh5VWdMY20yYjlkb2x4SmU5b1daCjM2dWJzUXJHd0FOWXFrQTZYcDRDTkd4a1pVZXFNRFdFMzlGbzBsaGJDaC9KY1JuY3NCdzUwY3Nua0Z5WEdWRHMKTnU5c3FqRTA4dGV5VGxkVzB1YU1LakdZWTNwbk5yeDJvNHJqQzQwenVrdWFLSngyY1VFN2xtMDVscllOeFVXVAptTkErQnlHOGthSzdkTDAzZlQ4ZzlxaWhick5UYlRHOExDNkJmcjhUbC8rUEFpK3V1ZFFzVFczbTIrMG1YQk9SCmlQN1IvajBQRVZ1RGpWUlNXY1Yxb1hIL1hCVldvelVaZ0JOeFRkVzFWRHlQVTdITE05MDd6ekxNWlJWSWQrNXcKL0h4ei83MENnWUVBMGhEWkEwWVRsYXdEeVNxUXJyZHllU2QvT1dUTzRmYnVxNXVEVlAyVndnTS9LUUxzcjlOMApTYTRnOEJ5ZWVYZE9QS1R4U0E0YS9BQ1h1bktRYUdTU2pUVVE5TDAxSjduUVE3MjNKaTdZVSswcE0zTEcrMEdhClBHV3h3bVRWTS9YY09DaE9kdjB1OEg1bVNKdzE0VUF3emJndVJIL1N3N3lUQ1pkWGpFN01DZHNDZ1lFQS8rc1IKUFdVcFBSeUNsSU9EMjBlZTQyMkNpYjgvVXR4NkZyRW5VS1luU2k5MGhDM2RJcTFUaStOQUhxVHRrRklWY0czSApQemNvYkVGc2pWZEVSWWM3UUdoRWt4Slk4NFY3bnVsR3VmTHVGMGs5dzBEdE0rY2x6TFNSN2pZS1NkT2RpSUphClUzemxudUF0MXdkUkxHVG9lQzY5aDVGSzMwWmtRM2F4YWt3ZmtSOENnWUVBbUVzZ21lLy9HTjZwcS9sUkJXbjMKOHdBQWk0S2JQbFZBdVdjNGNyQ2FGeHMxZWkwbG5WOUhDbmZVWjEvSVFMV1BJZ1pPNnZkVzl1WVRHbGdlZTZDVwpZd3RhN0tRVDJtWXJLRUZ0ZTZBd3M3L1h3L1h0YnBFa0dhOThqVHQvR25tZm01TVZOOHpjYi95amVQYlBWU3V0CmRpZVdXNUQwSTNZZWY3Q2FCeDNGYlVzQ2dZRUFoazk5UmNhQXhTVGdWMGRLZlZ2eVJKUGxyWnRraFgxV3lmQUIKblM4R2NjWEVGZGJvTnRuV2ZoVXZRcVgyVkFid1g0Z055TnlPNTNuU21iOVNBbGQ5dmtpNnJLRTFjK0Q3UnlSUQp6U2gwMGwzSy8xMWs0QmVRM0FWc2pTTnBkT09OeXVYMnQ5aFZ2bk1UTzhZSVVROUlma0t4ajZPdU1zNERzdkJwCkhrdURTYXNDZ1lBSk1LSkxEelZIRVZUb2tRSVlnZThaSzQvVHRiRCtPSHQxNzZRM2NXTmJSR1FQc0xubVdxQTIKOXd0dk9paWxNUFBoTVVjSUpEa3VpUms4RWUyVG4vQmZZNStzVmEvY2l3SCtMdldPSjlHVTJIQ0ZUeXNnejBkRQpuR0pNdEN6dGRjMkRxeG9GY0JUaFZUbVo4RjlYSVJtQkx4bWNIbFVZand3VFNwMFdvNHBwd0E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
{{- end }}
