{{- if .Values.maintenance.backup.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "meta.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "meta.name" . }}
    chart: {{ template "meta.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    team: {{ .Values.team }}
spec:
  schedule: {{ .Values.maintenance.backup.schedule }} 
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: {{ template "meta.name" . }}-load-backup
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.imagePullPolicy }}
            args:
            - "backup"
            - "--address={{ template "meta.name" . }}-maintenance:{{ .Values.maintenance.server.port }}"
            {{- if .Values.maintenance.token }}
            - "--token=$(TOKEN)"
            {{- end }}
            - "--ca=/maintenance-cert/ca.crt"
            - "--dir=/backup"
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            volumeMounts:
            - mountPath: /maintenance-cert
              name: maintenance-cert
            - mountPath: /backup
              name: backup
            {{- if .Values.maintenance.token }}
            env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "meta.name" . }}-maintenance-token
                  key: token
            {{- end }}
          containers:
          - name: {{ template "meta.name" . }}-store-backup
            image: "peakcom/s5cmd:v1.3.0"
            imagePullPolicy: {{ .Values.image.imagePullPolicy }}
            command:
            - /bin/sh
            - -c
            - >-
              CURR_DATE=$(date "+%y-%m-%d-%H-%M") &&              
              ln -s /backup/ /$CURR_DATE &&
              ./s5cmd cp /$CURR_DATE/ {{ .Values.maintenance.backup.bucket }}/
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            volumeMounts:
            - mountPath: /backup
              name: backup
          restartPolicy: OnFailure
          volumes:
          - name: backup
            emptyDir: {}
          - name: maintenance-cert
            secret:
              defaultMode: 420
              secretName: {{ template "meta.name" . }}-maintenance-cert
{{- end }}
