apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "meta.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "meta.name" . }}
    chart: {{ template "meta.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    team: {{ .Values.team }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "meta.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "meta.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "meta.name" . }}
      containers:
      - name: {{ template "meta.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args:
        - "--addr=0.0.0.0:{{ .Values.internalPort }}"
        - --cert-filename=/cert/tls.crt
        - --key-filename=/cert/tls.key
        ports:
        - name: https
          containerPort: {{ .Values.internalPort }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
          - mountPath: /cert
            name: cert
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ template "meta.name" . }}-cert
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
