apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "meta.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "meta.name" . }}
    chart: {{ template "meta.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    team: {{ .Values.team }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "meta.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "meta.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "meta.name" . }}
      containers:
      - name: {{ template "meta.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - name: http
          containerPort: 8080
        resources: {{- toYaml .Values.resources | nindent 10 }}

      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
