{{- if not .Values.kind }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "meta.name" . }}-logging
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "meta.name" . }}
    chart: {{ template "meta.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: fluentd
data:
  fluent.conf: |
    <filter $labels(app={{ template "meta.name" . }})>
      @type parser
      key_name log
      format json
      reserve_data true
      <parse>
        @type json
      </parse>
    </filter>

    <filter $labels(app={{ template "meta.name" . }})>
      @type record_transformer
      enable_ruby
      <record>
        LogLevel ${record["level"].upcase}
        message ${record["msg"]}
        log_timestamp ${record["ts"]}
      </record>
      remove_keys level, msg, ts
    </filter>

    <match $labels(app={{ template "meta.name" . }})>
      @type service-logs
    </match>
{{- end }}
