{{- if .Values.kafka.tls }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "meta.name" . }}-kafka-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "meta.name" . }}
    chart: {{ template "meta.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  encryptedData:
    ca.crt: {{ .Values.kafka.serverCert}}
    tls.crt: {{ .Values.kafka.clientCert}}
    tls.key: {{ .Values.kafka.clientKey}}
  template:
    type: kubernetes.io/tls
{{- end }}
{{- if and .Values.maintenance.backup.enabled .Values.maintenance.token }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "meta.name" . }}-maintenance-token
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "meta.name" . }}
    chart: {{ template "meta.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  encryptedData:
    token: {{ .Values.maintenance.token }}
{{- end }}
