apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "meta.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "meta.name" . }}
    chart: {{ template "meta.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    team: {{ .Values.team }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "meta.name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ template "meta.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "meta.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "meta.name" . }}
      containers:
      - name: {{ template "meta.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - "sh"
        - "-c"
        - >-
          NODE_ID=$(expr $(echo "${POD_NAME: -1}") + 1) &&
          regatta \
            --api.address=0.0.0.0:{{ .Values.internalPort }} \
            --api.cert-filename=/cert/tls.crt \
            --api.key-filename=/cert/tls.key \
            --raft.address=$(POD_NAME).{{ template "meta.name" . }}.{{ .Release.Namespace }}.svc.cluster.local:5012 \
            --raft.listen-address=0.0.0.0:5012 \
            --raft.node-id=${NODE_ID} \
            --raft.node-host-dir=/data/raft \
            --raft.initial-members={{ .Values.raft.initialMembers }} \
            --raft.state-machine-dir=/data/state-machine \
          {{- if .Values.reflectionAPI.enabled }}
            --api.reflection-api \
          {{- end }}
          {{- if .Values.kafka.enabled }}
            --kafka.brokers={{ .Values.kafka.brokers }} \
            --kafka.timeout={{ .Values.kafka.dialerTimeout }} \
            --kafka.group-id={{ .Values.kafka.groupID }} \
            --kafka.topics={{ .Values.kafka.topics }} \
            --kafka.tls={{ .Values.kafka.tls }} \
            --kafka.server-cert-filename=/kafka-cert/ca.crt \
            --kafka.client-cert-filename=/kafka-cert/tls.crt \
            --kafka.client-key-filename=/kafka-cert/tls.key
          {{- end }}
        ports:
        - name: https
          containerPort: {{ .Values.internalPort }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
        - mountPath: /cert
          name: cert
        {{- if ne .Values.kafka.serverCert ""}}
        - mountPath: /kafka-cert
          name: kafka-cert
        {{- end }}
        - mountPath: /data
          name: data
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ template "meta.name" . }}-cert
      {{- if ne .Values.kafka.serverCert ""}}
      - name: kafka-cert
        secret:
          defaultMode: 420
          secretName: {{ template "meta.name" . }}-kafka-cert
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{ if .Values.affinity }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: {{ template "meta.name" . }}
                release: {{ .Release.Name }}
      {{- end }}
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
    {{ .Values.persistence.storage | toYaml | nindent 6 }}
