apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "meta.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "meta.name" . }}
    chart: {{ template "meta.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    team: {{ .Values.team }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "meta.name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ template "meta.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "meta.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "meta.name" . }}
      containers:
      - name: {{ template "meta.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args:
        - "--addr=0.0.0.0:{{ .Values.internalPort }}"
        - --cert-filename=/cert/tls.crt
        - --key-filename=/cert/tls.key
        - --raft-address=127.0.0.1:5012
        - --node-host-dir=/data
        {{- if .Values.reflectionAPI.enabled }}
        - --reflection-api
        {{- end }}
        ports:
        - name: https
          containerPort: {{ .Values.internalPort }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /cert
          name: cert
        - mountPath: /data
          name: data
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ template "meta.name" . }}-cert
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
    {{ .Values.persistence.storage | toYaml | nindent 6 }}
