name: golangci-lint
on:
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: wandera/checkout@v2
      - name: golangci-lint
        uses: wandera/golangci-lint-action@v1
        with:
          version: v1.30
